import "./markdown-renderer.test";
import "./chat-ui-utils.test";
import "./model-fetcher.test";
import "./tool-call-parsing.test";
import "./settings-runtime.test";
import "./tool-round-limit.test";
import "./mcp-client.test";
import "./mcp-tool-names.test";
import "./local-cli-client.test";
import "./local-cli-fixes.test";
import "./local-cli-round2.test";
import "./local-cli-round3.test";
import "./local-cli-autostart.test";
import "./local-cli-instructions.test";
import "./local-cli-resume.test";
import "./chat-request-owner.test";
import "./pending-save.test";
import "./branch-switch.test";
import "./session-select-race.test";
import "./workdir.test";
import "./local-image-paths.test";
import "./token-speed.test";
import "./local-cli-tool-summary.test";
import "./local-cli-review4.test";
import { run } from "./test-harness";

await run();
