import "./query-converters.test";
import "./query-builder.test";
import "./query-advanced.test";
import "./queryBlocksByTag.test";
import "./markdown-renderer.test";
import "./chat-ui-utils.test";
import "./model-fetcher.test";
import "./tool-call-parsing.test";
import "./settings-runtime.test";
import "./tool-round-limit.test";
import "./mcp-client.test";
import "./mcp-tool-names.test";
import "./local-cli-client.test";
import "./local-cli-fixes.test";
import "./local-cli-round2.test";
import "./local-cli-round3.test";
import "./local-cli-autostart.test";
import "./local-cli-instructions.test";
import "./chat-request-owner.test";
import { run } from "./test-harness";

await run();
